In [43]:
import pandas as pd
import json 
import os

In [14]:

def extract_audio_links(folder_path, output_file):
    """
    Extract audio links from JSON files in the specified folder
    and create a combined JSON with {filename: audio_link} format.
    """
    # Dictionary to store filename: audio link pairs
    audio_links = {}
    
    # Check if the folder exists
    if not os.path.exists(folder_path):
        print(f"Error: Folder '{folder_path}' not found.")
        return None
    
    # Iterate through all files in the folder
    for filename in os.listdir(folder_path):
        # Only process JSON files
        if filename.endswith('.json'):
            file_path = os.path.join(folder_path, filename)
            
            try:
                # Read and parse the JSON file
                with open(file_path, 'r', encoding='utf-8') as file:
                    try:
                        data = json.load(file)
                        
                        # Extract the audio link
                        if (
                            'data' in data and 
                            'body' in data['data'] and 
                            'URL' in data['data']['meta_data']
                        ):
                            audio_link = data['data']['meta_data']['URL']
                            
                            # Only add to the dictionary if there's a valid audio link
                            if audio_link and audio_link != "":
                                # Remove the .json extension from the filename
                                filename_without_extension = os.path.splitext(filename)[0]
                                audio_links[filename_without_extension] = audio_link
                                
                    except json.JSONDecodeError:
                        print(f"Error: Unable to parse JSON in file '{filename}'")
            except Exception as e:
                print(f"Error processing file '{filename}': {str(e)}")
    
    # Write the combined data to a new JSON file
    
    # output_file = f"{categ}_combined_audio_links.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(audio_links, f, ensure_ascii=False, indent=4)
    
    print(f"Successfully created '{output_file}' with {len(audio_links)} all article links.")
    return audio_links, len(audio_links)

In [26]:
categ = "བོད།"
folder_path = f"./new_data/{categ}/"
file_name = f"{categ}_combined_all_articles_links.json"
output_file = "./new_data/" + file_name

first_links, file_with_audio = extract_audio_links(folder_path, output_file)

Successfully created './new_data/བོད།_combined_all_articles_links.json' with 7261 all article links.

In [16]:
categ = "འཛམ་གླིང་།"
folder_path = f"./new_data/{categ}/"
file_name = f"{categ}_combined_all_articles_links.json"
output_file = "./new_data/" + file_name

second_links, file_with_audio = extract_audio_links(folder_path, output_file)

Successfully created './new_data/འཛམ་གླིང་།_combined_all_articles_links.json' with 8381 all article links.

In [17]:
categ = "ཨ་རི།"
folder_path = f"./new_data/{categ}/"
file_name = f"{categ}_combined_all_articles_links.json"
output_file = "./new_data/" + file_name

third_links, file_with_audio = extract_audio_links(folder_path, output_file)

Successfully created './new_data/ཨ་རི།_combined_all_articles_links.json' with 8265 all article links.

In [18]:
categ = "རྒྱ་ནག"
folder_path = f"./new_data/{categ}/"
file_name = f"{categ}_combined_all_articles_links.json"
output_file = "./new_data/" + file_name

forth_links, file_with_audio = extract_audio_links(folder_path, output_file)

Successfully created './new_data/རྒྱ་ནག_combined_all_articles_links.json' with 7212 all article links.

In [32]:
first_list = []
for keys, links in first_links.items():
    first_list.append(links)

print("total links", len(first_list))
print("duplicates in own category", len(set(first_list)))

total links 7261
duplicates in own category 7261

In [33]:
second_list = []
for keys, links in second_links.items():
    second_list.append(links)


print("total links", len(second_list))
print("duplicates in own category", len(set(second_list)))

total links 8381
duplicates in own category 8381

In [34]:
third_list = []
for keys, links in third_links.items():
    third_list.append(links)

print("total links", len(third_list))
print("duplicates in own category", len(set(third_list)))

total links 8265
duplicates in own category 8265

In [35]:
forth_list = []
for keys, links in forth_links.items():
    forth_list.append(links)

print("total links", len(forth_list))
print("duplicates in own category", len(set(forth_list)))

total links 7212
duplicates in own category 7212

In [37]:
total_links = len(forth_list) + len(third_list) + len(second_list) + len(first_list)
print(f"total links {total_links}")

total links 31119

# finding duplicates in inter categories

In [42]:
all_links = set()
all_links.update(first_list)
all_links.update(second_list)
all_links.update(third_list)
all_links.update(forth_list)

non_dup_links  = len(all_links)
print(f"final links after removing duplicates {non_dup_links}")
print(f"removed duplicates {total_links-non_dup_links} - \npercentage: {round((total_links-non_dup_links)/total_links, 2)*100}% duplicates values")

final links after removing duplicates 10535
removed duplicates 20584 -
percentage: 66.0% duplicates values

## making all the data as one df so we can filter it

In [47]:
# Convert to DataFrame
df_1st = pd.DataFrame(list(first_links.items()), columns=['file_name', 'links'])
df_1st["data_path"] = "./new_data/བོད།/"
df_1st["audio_path"] = "./new_data/audio/བོད།/"
df_1st.head()

,file_name,links,data_path,audio_path
0,VOT_Tib_བོད།_0,https://www.voatibetan.com/a/nepal-gelukpa-bud...,./new_data/བོད།/,./new_data/audio/བོད།/
1,VOT_Tib_བོད།_1,https://www.voatibetan.com/a/tibetan-environme...,./new_data/བོད།/,./new_data/audio/བོད།/
2,VOT_Tib_བོད།_2,https://www.voatibetan.com/a/global-solidarity...,./new_data/བོད།/,./new_data/audio/བོད།/
3,VOT_Tib_བོད།_3,https://www.voatibetan.com/a/un-report-china-e...,./new_data/བོད།/,./new_data/audio/བོད།/
4,VOT_Tib_བོད།_4,https://www.voatibetan.com/a/swiss-government-...,./new_data/བོད།/,./new_data/audio/བོད།/

In [48]:
# Convert to DataFrame
df_2 = pd.DataFrame(list(second_links.items()), columns=['file_name', 'links'])
df_2["data_path"] = "./new_data/འཛམ་གླིང་།/"
df_2["audio_path"] = "./new_data/audio/འཛམ་གླིང་།/"
df_2.head()

,file_name,links,data_path,audio_path
0,VOT_Tib_འཛམ་གླིང་།_0,https://www.voatibetan.com/a/what-does-it-mean...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/
1,VOT_Tib_འཛམ་གླིང་།_1,https://www.voatibetan.com/a/russian-president...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/
2,VOT_Tib_འཛམ་གླིང་།_2,https://www.voatibetan.com/a/funding-cuts-impa...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/
3,VOT_Tib_འཛམ་གླིང་།_3,https://www.voatibetan.com/a/voa-exclusive-on-...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/
4,VOT_Tib_འཛམ་གླིང་།_4,https://www.voatibetan.com/a/eu-hits-back-at-t...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/

In [49]:
# Convert to DataFrame
df_3 = pd.DataFrame(list(third_links.items()), columns=['file_name', 'links'])
df_3["data_path"] = "./new_data/ཨ་རི།/"
df_3["audio_path"] = "./new_data/audio/ཨ་རི།/"
df_3.head()

,file_name,links,data_path,audio_path
0,VOT_Tib_ཨ་རི།_0,https://www.voatibetan.com/a/trump-vows-to-dep...,./new_data/ཨ་རི།/,./new_data/audio/ཨ་རི།/
1,VOT_Tib_ཨ་རི།_1,https://www.voatibetan.com/a/voa-exclusive-sta...,./new_data/ཨ་རི།/,./new_data/audio/ཨ་རི།/
2,VOT_Tib_ཨ་རི།_2,https://www.voatibetan.com/a/the-u-s-justice-d...,./new_data/ཨ་རི།/,./new_data/audio/ཨ་རི།/
3,VOT_Tib_ཨ་རི།_3,https://www.voatibetan.com/a/remarks-at-the-st...,./new_data/ཨ་རི།/,./new_data/audio/ཨ་རི།/
4,VOT_Tib_ཨ་རི།_4,https://www.voatibetan.com/a/foreign-adversari...,./new_data/ཨ་རི།/,./new_data/audio/ཨ་རི།/

In [50]:
# Convert to DataFrame
df_4 = pd.DataFrame(list(forth_links.items()), columns=['file_name', 'links'])
df_4["data_path"] = "./new_data/རྒྱ་ནག/"
df_4["audio_path"] = "./new_data/audio/རྒྱ་ནག/"
df_4.head()

,file_name,links,data_path,audio_path
0,VOT_Tib_རྒྱ་ནག_0,https://www.voatibetan.com/a/taiwan-labels-chi...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
1,VOT_Tib_རྒྱ་ནག_1,https://www.voatibetan.com/a/china-s-national-...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
2,VOT_Tib_རྒྱ་ནག_2,https://www.voatibetan.com/a/hong-kong-democra...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
3,VOT_Tib_རྒྱ་ནག_3,https://www.voatibetan.com/a/trump-s-taiwan-po...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
4,VOT_Tib_རྒྱ་ནག_4,https://www.voatibetan.com/a/us-pacific-comman...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/

## merge all

In [52]:
merged_df = pd.concat([df_1st, df_2, df_3, df_4])
merged_df.shape

(31119, 4)

In [53]:
clean_merged_df = merged_df.drop_duplicates(subset=['links'])
clean_merged_df.shape

(10535, 4)

In [55]:
clean_merged_df.sample(10)

,file_name,links,data_path,audio_path
1361,VOT_Tib_བོད།_1361,https://www.voatibetan.com/a/un-experts-raise-...,./new_data/བོད།/,./new_data/audio/བོད།/
1239,VOT_Tib_བོད།_1239,https://www.voatibetan.com/a/tibetan-urged-to-...,./new_data/བོད།/,./new_data/audio/བོད།/
63,VOT_Tib_རྒྱ་ནག_63,https://www.voatibetan.com/a/china-s-central-b...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
4185,VOT_Tib_བོད།_4185,https://www.voatibetan.com/a/2692906.html,./new_data/བོད།/,./new_data/audio/བོད།/
6339,VOT_Tib_འཛམ་གླིང་།_6339,https://www.voatibetan.com/a/mps-urge-canadian...,./new_data/འཛམ་གླིང་།/,./new_data/audio/འཛམ་གླིང་།/
1327,VOT_Tib_བོད།_1327,https://www.voatibetan.com/a/china-expels-tibe...,./new_data/བོད།/,./new_data/audio/བོད།/
4276,VOT_Tib_བོད།_4276,https://www.voatibetan.com/a/2625046.html,./new_data/བོད།/,./new_data/audio/བོད།/
178,VOT_Tib_རྒྱ་ནག_178,https://www.voatibetan.com/a/a-china-plans-to-...,./new_data/རྒྱ་ནག/,./new_data/audio/རྒྱ་ནག/
2804,VOT_Tib_བོད།_2804,https://www.voatibetan.com/a/4499425.html,./new_data/བོད།/,./new_data/audio/བོད།/
6187,VOT_Tib_བོད།_6187,https://www.voatibetan.com/a/tibetan-rights-gr...,./new_data/བོད།/,./new_data/audio/བོད།/

In [59]:
file_name = "VOATibetan_data_map.csv"
clean_data_dir = './new_data/clean_data/'
clean_merged_df.to_csv(clean_data_dir + file_name, index=False)

In [56]:
import pandas as pd
import shutil
import os

In [57]:
import pandas as pd
import shutil
import os


# Define the clean data destination directory
clean_data_dir = './new_data/clean_data/'

# Create the clean data directory if it doesn't exist
os.makedirs(clean_data_dir, exist_ok=True)

# Iterate through the DataFrame rows
for index, row in clean_merged_df.iterrows():
    # Construct source and destination file paths
    json_source = f"{row['data_path']}{row['file_name']}.json"
    audio_source = f"{row['audio_path']}{row['file_name']}.mp3"
    
    json_dest = f"{clean_data_dir}{row['file_name']}.json"
    audio_dest = f"{clean_data_dir}{row['file_name']}.mp3"
    
    # Copy JSON file
    try:
        shutil.copy2(json_source, json_dest)
        print(f"Copied JSON: {json_source} -> {json_dest}")
    except FileNotFoundError:
        print(f"JSON file not found: {json_source}")
    except Exception as e:
        print(f"Error copying JSON {json_source}: {str(e)}")
    
    # Copy MP3 file
    try:
        shutil.copy2(audio_source, audio_dest)
        print(f"Copied MP3: {audio_source} -> {audio_dest}")
    except FileNotFoundError:
        print(f"MP3 file not found: {audio_source}")
    except Exception as e:
        print(f"Error copying MP3 {audio_source}: {str(e)}")

print("File copying complete!")

Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_0.json -> ./new_data/clean_data/VOT_Tib_བོད།_0.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_0.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_1.json -> ./new_data/clean_data/VOT_Tib_བོད།_1.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_1.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_2.json -> ./new_data/clean_data/VOT_Tib_བོད།_2.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_2.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_3.json -> ./new_data/clean_data/VOT_Tib_བོད།_3.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_3.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_4.json -> ./new_data/clean_data/VOT_Tib_བོད།_4.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_4.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_5.json -> ./new_data/clean_data/VOT_Tib_བོད།_5.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_5.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_6.json -> ./new_data/clean_data/VOT_Tib_བོད།_6.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_6.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_7.json -> ./new_data/clean_data/VOT_Tib_བོད།_7.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_7.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_7.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_8.json -> ./new_data/clean_data/VOT_Tib_བོད།_8.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_8.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_8.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_9.json -> ./new_data/clean_data/VOT_Tib_བོད།_9.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_9.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_9.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_10.json -> ./new_data/clean_data/VOT_Tib_བོད།_10.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_10.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_10.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_11.json -> ./new_data/clean_data/VOT_Tib_བོད།_11.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_11.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_11.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_12.json -> ./new_data/clean_data/VOT_Tib_བོད།_12.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_12.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_13.json -> ./new_data/clean_data/VOT_Tib_བོད།_13.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_13.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_14.json -> ./new_data/clean_data/VOT_Tib_བོད།_14.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_14.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_15.json -> ./new_data/clean_data/VOT_Tib_བོད།_15.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_15.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_16.json -> ./new_data/clean_data/VOT_Tib_བོད།_16.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_16.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_16.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_17.json -> ./new_data/clean_data/VOT_Tib_བོད།_17.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_17.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_18.json -> ./new_data/clean_data/VOT_Tib_བོད།_18.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_18.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_19.json -> ./new_data/clean_data/VOT_Tib_བོད།_19.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_19.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_19.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_20.json -> ./new_data/clean_data/VOT_Tib_བོད།_20.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_20.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_21.json -> ./new_data/clean_data/VOT_Tib_བོད།_21.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_21.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_21.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_22.json -> ./new_data/clean_data/VOT_Tib_བོད།_22.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_22.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_23.json -> ./new_data/clean_data/VOT_Tib_བོད།_23.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_23.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_24.json -> ./new_data/clean_data/VOT_Tib_བོད།_24.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_24.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_24.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_25.json -> ./new_data/clean_data/VOT_Tib_བོད།_25.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_25.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_26.json -> ./new_data/clean_data/VOT_Tib_བོད།_26.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_26.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_26.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_27.json -> ./new_data/clean_data/VOT_Tib_བོད།_27.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_27.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_27.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_28.json -> ./new_data/clean_data/VOT_Tib_བོད།_28.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_28.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_29.json -> ./new_data/clean_data/VOT_Tib_བོད།_29.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_29.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_29.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_30.json -> ./new_data/clean_data/VOT_Tib_བོད།_30.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_30.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_31.json -> ./new_data/clean_data/VOT_Tib_བོད།_31.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_31.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_31.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_32.json -> ./new_data/clean_data/VOT_Tib_བོད།_32.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_32.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_33.json -> ./new_data/clean_data/VOT_Tib_བོད།_33.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_33.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_34.json -> ./new_data/clean_data/VOT_Tib_བོད།_34.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_34.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_35.json -> ./new_data/clean_data/VOT_Tib_བོད།_35.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_35.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_36.json -> ./new_data/clean_data/VOT_Tib_བོད།_36.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_36.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_36.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_37.json -> ./new_data/clean_data/VOT_Tib_བོད།_37.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_37.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_37.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_38.json -> ./new_data/clean_data/VOT_Tib_བོད།_38.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_38.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_38.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_39.json -> ./new_data/clean_data/VOT_Tib_བོད།_39.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_39.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_40.json -> ./new_data/clean_data/VOT_Tib_བོད།_40.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_40.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_40.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_41.json -> ./new_data/clean_data/VOT_Tib_བོད།_41.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_41.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_41.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_42.json -> ./new_data/clean_data/VOT_Tib_བོད།_42.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_42.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_43.json -> ./new_data/clean_data/VOT_Tib_བོད།_43.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_43.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_43.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_44.json -> ./new_data/clean_data/VOT_Tib_བོད།_44.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_44.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_45.json -> ./new_data/clean_data/VOT_Tib_བོད།_45.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_45.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_45.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_46.json -> ./new_data/clean_data/VOT_Tib_བོད།_46.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_46.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_46.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_47.json -> ./new_data/clean_data/VOT_Tib_བོད།_47.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_47.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_47.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_48.json -> ./new_data/clean_data/VOT_Tib_བོད།_48.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_48.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_49.json -> ./new_data/clean_data/VOT_Tib_བོད།_49.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_49.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_49.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_50.json -> ./new_data/clean_data/VOT_Tib_བོད།_50.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_50.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_50.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_51.json -> ./new_data/clean_data/VOT_Tib_བོད།_51.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_51.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_51.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_52.json -> ./new_data/clean_data/VOT_Tib_བོད།_52.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_52.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_52.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_53.json -> ./new_data/clean_data/VOT_Tib_བོད།_53.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_53.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_53.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_54.json -> ./new_data/clean_data/VOT_Tib_བོད།_54.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_54.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_54.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_55.json -> ./new_data/clean_data/VOT_Tib_བོད།_55.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_55.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_55.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_56.json -> ./new_data/clean_data/VOT_Tib_བོད།_56.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_56.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_57.json -> ./new_data/clean_data/VOT_Tib_བོད།_57.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_57.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_57.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_58.json -> ./new_data/clean_data/VOT_Tib_བོད།_58.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_58.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_58.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_59.json -> ./new_data/clean_data/VOT_Tib_བོད།_59.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_59.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_59.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_60.json -> ./new_data/clean_data/VOT_Tib_བོད།_60.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_60.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_60.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_61.json -> ./new_data/clean_data/VOT_Tib_བོད།_61.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_61.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_61.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_62.json -> ./new_data/clean_data/VOT_Tib_བོད།_62.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_62.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_62.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_63.json -> ./new_data/clean_data/VOT_Tib_བོད།_63.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_63.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_64.json -> ./new_data/clean_data/VOT_Tib_བོད།_64.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_64.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_64.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_65.json -> ./new_data/clean_data/VOT_Tib_བོད།_65.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_65.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_66.json -> ./new_data/clean_data/VOT_Tib_བོད།_66.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_66.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_66.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_67.json -> ./new_data/clean_data/VOT_Tib_བོད།_67.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_67.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_68.json -> ./new_data/clean_data/VOT_Tib_བོད།_68.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_68.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_68.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_69.json -> ./new_data/clean_data/VOT_Tib_བོད།_69.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_69.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_69.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_70.json -> ./new_data/clean_data/VOT_Tib_བོད།_70.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_70.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_71.json -> ./new_data/clean_data/VOT_Tib_བོད།_71.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_71.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_71.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_72.json -> ./new_data/clean_data/VOT_Tib_བོད།_72.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_72.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_73.json -> ./new_data/clean_data/VOT_Tib_བོད།_73.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_73.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_74.json -> ./new_data/clean_data/VOT_Tib_བོད།_74.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_74.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_74.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_75.json -> ./new_data/clean_data/VOT_Tib_བོད།_75.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_75.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_75.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_76.json -> ./new_data/clean_data/VOT_Tib_བོད།_76.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_76.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_76.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_77.json -> ./new_data/clean_data/VOT_Tib_བོད།_77.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_77.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_77.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_78.json -> ./new_data/clean_data/VOT_Tib_བོད།_78.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_78.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_78.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_79.json -> ./new_data/clean_data/VOT_Tib_བོད།_79.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_79.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_79.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_80.json -> ./new_data/clean_data/VOT_Tib_བོད།_80.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_80.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_80.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_81.json -> ./new_data/clean_data/VOT_Tib_བོད།_81.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_81.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_82.json -> ./new_data/clean_data/VOT_Tib_བོད།_82.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_82.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_82.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_83.json -> ./new_data/clean_data/VOT_Tib_བོད།_83.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_83.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_83.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_84.json -> ./new_data/clean_data/VOT_Tib_བོད།_84.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_84.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_84.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_85.json -> ./new_data/clean_data/VOT_Tib_བོད།_85.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_85.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_85.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_86.json -> ./new_data/clean_data/VOT_Tib_བོད།_86.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_86.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_86.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_87.json -> ./new_data/clean_data/VOT_Tib_བོད།_87.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_87.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_88.json -> ./new_data/clean_data/VOT_Tib_བོད།_88.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_88.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_88.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_89.json -> ./new_data/clean_data/VOT_Tib_བོད།_89.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_89.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_89.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_90.json -> ./new_data/clean_data/VOT_Tib_བོད།_90.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_90.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_90.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_91.json -> ./new_data/clean_data/VOT_Tib_བོད།_91.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_91.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_92.json -> ./new_data/clean_data/VOT_Tib_བོད།_92.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_92.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_92.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_93.json -> ./new_data/clean_data/VOT_Tib_བོད།_93.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_93.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_94.json -> ./new_data/clean_data/VOT_Tib_བོད།_94.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_94.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_94.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_95.json -> ./new_data/clean_data/VOT_Tib_བོད།_95.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_95.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_96.json -> ./new_data/clean_data/VOT_Tib_བོད།_96.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_96.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_96.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_97.json -> ./new_data/clean_data/VOT_Tib_བོད།_97.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_97.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_98.json -> ./new_data/clean_data/VOT_Tib_བོད།_98.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_98.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_99.json -> ./new_data/clean_data/VOT_Tib_བོད།_99.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_99.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_99.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_100.json -> ./new_data/clean_data/VOT_Tib_བོད།_100.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_100.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_100.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_101.json -> ./new_data/clean_data/VOT_Tib_བོད།_101.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_101.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_102.json -> ./new_data/clean_data/VOT_Tib_བོད།_102.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_102.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_102.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_103.json -> ./new_data/clean_data/VOT_Tib_བོད།_103.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_103.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_103.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_104.json -> ./new_data/clean_data/VOT_Tib_བོད།_104.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_104.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_104.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_105.json -> ./new_data/clean_data/VOT_Tib_བོད།_105.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_105.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_105.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_106.json -> ./new_data/clean_data/VOT_Tib_བོད།_106.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_106.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_106.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_107.json -> ./new_data/clean_data/VOT_Tib_བོད།_107.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_107.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_107.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_108.json -> ./new_data/clean_data/VOT_Tib_བོད།_108.json
MP3 file not found: ./new_data/audio/བོད།/VOT_Tib_བོད།_108.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_109.json -> ./new_data/clean_data/VOT_Tib_བོད།_109.json
Copied MP3: ./new_data/audio/བོད།/VOT_Tib_བོད།_109.mp3 -> ./new_data/clean_data/VOT_Tib_བོད།_109.mp3
Copied JSON: ./new_data/བོད།/VOT_Tib_བོད།_110.json -> ./new_data/clean_data/VOT_Tib_བོད།_110.json